[toolchain]
channel = "1.98.1"
components = ["rustfmt", "clippy"]
profile = "minimal"
targets = ["aarch64-linux-android", "armv7-linux-androideabi", "i686-linux-android", "x86_64-linux-android", "aarch64-apple-ios", "aarch64-apple-ios-sim", "x86_64-apple-ios"]
